name       : marble
version    : 19.08.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/marble-19.08.0.tar.xz : c1c951a1357c94a61b38f0ae8a1235d194150cd351dbf25d2db3508b22b44cc1
license    : LGPL-2.1-or-later
component  : network.web
summary    : Virtual Globe and World Atlas
description: |
    Marble is a Virtual Globe and World Atlas that you can use to learn more about Earth: You can pan and zoom around and you can look up places and roads.
patterns   :
    - libs : /usr/lib64/lib*.so.*
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_MARBLE_TOOLS=YES \
                -DBUILD_MARBLE_TESTS=OFF \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
