name       : marble
version    : 22.04.3
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/marble-22.04.3.tar.xz : 438d4ef317231b8f2377f64ebfe9249ce669103fb71105c9d7de35a39bbef771
homepage   : https://kde.org/applications/education/org.kde.marble
license    : LGPL-2.1-or-later
component  :
    - network.web
    - libs : programming.library
summary    : Virtual Globe and World Atlas
description: |
    Marble is a Virtual Globe and World Atlas that you can use to learn more about Earth: You can pan and zoom around and you can look up places and roads.
patterns   :
    - libs : /usr/lib64/lib*.so*
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_MARBLE_TOOLS=YES \
                -DBUILD_MARBLE_TESTS=OFF \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
