name       : marble
version    : 19.08.3
release    : 33
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/marble-19.08.3.tar.xz : cd5d7f758d2234dc8e2fa638b9e1326461655e10dbe21910dbef029e80ef7a68
license    : LGPL-2.1-or-later
component  : network.web
summary    : Virtual Globe and World Atlas
description: |
    Marble is a Virtual Globe and World Atlas that you can use to learn more about Earth: You can pan and zoom around and you can look up places and roads.
patterns   :
    - libs : /usr/lib64/lib*.so.*
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_MARBLE_TOOLS=YES \
                -DBUILD_MARBLE_TESTS=OFF \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
